AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create sns topic and subscription

Parameters:
  EmailAddress:
    Type: String
    Description: Email address for endpoint

Resources:
  SendEmailNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: "email"
      TopicName: "send_email_notification"

  SendEmailNotificationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SendEmailNotificationTopic
      PolicyDocument:
        Id: SendEmailNotificationTopicPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: Stmt1643807474528
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action:
              - sns:Publish
            Resource: !Ref SendEmailNotificationTopic
    DependsOn: SendEmailNotificationTopic

Outputs:
  Arn:
    Description: The ARN of the Lambda function that describes log groups.
    Value: !Ref SendEmailNotificationTopic
    Export:
      Name: SendEmailNotificationTopic
