AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create sns topic and subscription

Parameters:
  EmailAddress:
    Type: String
    Description: Email address for endpoint

Resources:
  SendEmailNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: "email"
      TopicName: "send_email_notification"

Outputs:
  Arn:
    Description: The ARN of the Lambda function that describes log groups.
    Value: !Ref SendEmailNotificationTopic
    Export:
      Name: SendEmailNotificationTopic
