AWSTemplateFormatVersion: '2010-09-09'
Description: This stack create CreateExportTaskLambda function.

Parameters:
  BucketName:
    Type: String
    Description: Name for the logs bucket.
  S3BucketParam:
    Type: String
    Description: Name of bucket which the lambda code is stored
  S3KeyParam:
    Type: String
    Description: The object key prefix

Resources:
  CreateExportTaskLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CreateExportTask
      Runtime: python3.9
      Timeout: 900
      Role: 
        Fn::GetAtt: 
          - "LambdaExecutionRole"
          - "Arn"
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Handler: create_export_task.lambda_handler
      Code:
        S3Bucket: 
          !Ref S3BucketParam
        S3Key: 
          !Ref S3KeyParam

      Description: Invoke a function during stack creation.
      TracingConfig:
        Mode: Active

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLogsDescribeExportTasks
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - "logs:CreateExportTask"
              Resource: "arn:aws:logs:*:*:*"

Outputs:
  Arn:
    Description: The ARN of the Lambda function that create export task.
    Value: !GetAtt CreateExportTaskLambda.Arn
    Export:
      Name: CreateExportTaskLambda
