AWSTemplateFormatVersion: "2010-09-09"

Description: This stack create event rule to publish the message when the state machine fails or time out

Parameters:
  StepFunctionsStateMachineArn:
    Type: String
    Description: The StepFunctions StateMachine Arn to set target
  SendEmailNotificationTopicArn:
    Type: String
    Description: An arn of sns topic for the target

Resources:
  FailOrTimeOutNotificationEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: "This event rule is triggered when the state machine fails or time out"
      EventBusName: default
      EventPattern:
        source:
          - aws.states
        detail-type:
          - Step Functions Execution Status Change
        detail:
          status:
            - "TIMED_OUT"
            - "FAILED"
          stateMachineArn:
            - !Ref StepFunctionsStateMachineArn
      State: ENABLED
      Targets:
        - Arn: !Ref SendEmailNotificationTopicArn
          Id: FailOrTimeOutNotificationEventRule
